In [31]:
import numpy as np

In [32]:
N = 3

In [33]:
A = np.zeros((N,N))

In [34]:
b = np.zeros(N)

In [35]:
x = np.zeros(N)

In [36]:
A[0,0] = 0;
A[0,1] = -1;
A[0,2] = 2;
A[1,0] = 3;
A[1,1] = 5;
A[1,2] = 0;
A[2,0] = 4;
A[2,1] = 2;
A[2,2] = 1;


In [37]:
b[0] = 1;
b[1]=2;
b[2]=3;

In [38]:
scale = np.zeros(N)
index = np.zeros(N)

In [39]:
A

array([[ 0., -1.,  2.],
       [ 3.,  5.,  0.],
       [ 4.,  2.,  1.]])

In [40]:
for i in range(N):
    s=0;
    index[i] = int(i);
    for j in range(N):
        if(np.abs(A[i,j])>s):
            s = np.abs(A[i,j]);
    scale[i] = s;
        

In [41]:
signdet = 1;

for k in range(N): #Pivoting
    ratiomax = 0.0;
    jpivot = k;
    for i in range(k,N):
        inj = int(index[i]);
        ratio = np.abs(A[inj,k])/scale[inj];
        if(ratio>ratiomax):
            jpivot = i;
            ratiomax = ratio;
    indexj = int(index[k]);
    if(jpivot != k):
        indexj = int(index[jpivot]);
        index[jpivot] = int(index[k]);
        index[k]=indexj;
        signdet = signdet*(-1);
        
    for i in range(k+1): #Forward Elimination
        ind = int(index[i])
        coeff = A[ind,k]/A[indexj,k];
        for j in range(k+1):
            A[ind,j] -= coeff*A[indexj,j];
        A[ind,k]=coeff;
        b[ind]-=A[ind,k]*b[indexj];
    
    #Determinant is the product of diagonal elements
    determ = signdet;
    for m in range(N):
        o = int(index[m])
        determ *= A[o,m]
    
    #perform backsubstitution
    
    x[N-1] = b[int(index[N-1])]/A[int(index[N-1]),N-1]
    print(x)
    for i in range(1,N):
        k = N -i;
        summ = b[int(index[k])];
        for j in range(k+1,N):
            summ -= A[int(index[k]),j]*x[j];
        x[k] = summ/A[int(index[k]),k]
        

[0.  0.  0.5]
[0.  0.4 0.5]
[0. 0. 0.]


In [42]:
x

array([0., 0., 0.])

In [43]:
A

array([[ 0. ,  0. ,  1. ],
       [ 0. ,  1. ,  0. ],
       [-0.2,  0.9,  0.5]])

In [44]:
b

array([ 0. ,  0. , -1.3])