In [122]:
import numpy as np

In [123]:
N=4

In [124]:
A= np.array([[1,3,4,6],[0,-91,51,9],[0,10**(-8),198,19],[0,7,76,541]])

In [125]:
A

array([[ 1.00e+00,  3.00e+00,  4.00e+00,  6.00e+00],
       [ 0.00e+00, -9.10e+01,  5.10e+01,  9.00e+00],
       [ 0.00e+00,  1.00e-08,  1.98e+02,  1.90e+01],
       [ 0.00e+00,  7.00e+00,  7.60e+01,  5.41e+02]])

In [126]:
x = np.array(['x1','x2','x3','x4'])

In [127]:
y = np.array(['y1','y2','y3','y4'])

In [128]:
def swaprow(A,B,pre,swap):
    b = A[pre].copy();
    A[pre] = A[swap];
    A[swap] = b;
    
    temp = B[pre];
    B[pre] = B[swap];
    B[swap] = temp;

In [129]:
def swapcol(my_array,x,colpre,colswap):
    temp = np.copy(my_array[:, colpre])
    my_array[:, colpre] = my_array[:, colswap]
    my_array[:, colswap] = temp
    
    emp = x[colpre];
    x[colpre] = x[colswap];
    x[colswap] = emp;

In [130]:
for i in range(N):
    largest = 0.0;
    row =0;
    col =0;
    for j in range(i,N):
        if(np.abs(A[j,i])>largest):
            if(A[i,j]>10**-2):
                largest = np.abs(A[j,i]);
                great = j;
                row =1;
    for j in range(i,N):       
        if(np.abs(A[i,j]>largest)):
            if(A[j,i]>10**-2):
                largest = np.abs(A[i,j]);
                great = j;
                col =1;
    print(col,row,great,largest)
    
    if(col == 1):
        swapcol(A,x,i,great)
    else:
        swaprow(A,y,i,great)
    print(i,A)     

0 1 0 1.0
0 [[ 1.00e+00  3.00e+00  4.00e+00  6.00e+00]
 [ 0.00e+00 -9.10e+01  5.10e+01  9.00e+00]
 [ 0.00e+00  1.00e-08  1.98e+02  1.90e+01]
 [ 0.00e+00  7.00e+00  7.60e+01  5.41e+02]]
1 1 3 9.0
1 [[ 1.00e+00  6.00e+00  4.00e+00  3.00e+00]
 [ 0.00e+00  9.00e+00  5.10e+01 -9.10e+01]
 [ 0.00e+00  1.90e+01  1.98e+02  1.00e-08]
 [ 0.00e+00  5.41e+02  7.60e+01  7.00e+00]]
0 1 2 198.0
2 [[ 1.00e+00  6.00e+00  4.00e+00  3.00e+00]
 [ 0.00e+00  9.00e+00  5.10e+01 -9.10e+01]
 [ 0.00e+00  1.90e+01  1.98e+02  1.00e-08]
 [ 0.00e+00  5.41e+02  7.60e+01  7.00e+00]]
0 1 3 7.0
3 [[ 1.00e+00  6.00e+00  4.00e+00  3.00e+00]
 [ 0.00e+00  9.00e+00  5.10e+01 -9.10e+01]
 [ 0.00e+00  1.90e+01  1.98e+02  1.00e-08]
 [ 0.00e+00  5.41e+02  7.60e+01  7.00e+00]]


In [131]:
A

array([[ 1.00e+00,  6.00e+00,  4.00e+00,  3.00e+00],
       [ 0.00e+00,  9.00e+00,  5.10e+01, -9.10e+01],
       [ 0.00e+00,  1.90e+01,  1.98e+02,  1.00e-08],
       [ 0.00e+00,  5.41e+02,  7.60e+01,  7.00e+00]])

In [132]:
y

array(['y1', 'y2', 'y3', 'y4'], dtype='<U2')

In [133]:
x

array(['x1', 'x4', 'x3', 'x2'], dtype='<U2')